# Generated by Django 2.0.3 on 2018-03-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_prn', '0003_auto_20180121_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='deathreport',
            name='parent_tracking_identifier',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='deathreport',
            name='related_tracking_identifier',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='deathreporttmg',
            name='parent_tracking_identifier',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='deathreporttmg',
            name='related_tracking_identifier',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicaldeathreport',
            name='parent_tracking_identifier',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicaldeathreport',
            name='related_tracking_identifier',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicaldeathreporttmg',
            name='parent_tracking_identifier',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicaldeathreporttmg',
            name='related_tracking_identifier',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicalprotocoldeviationviolation',
            name='parent_tracking_identifier',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicalprotocoldeviationviolation',
            name='related_tracking_identifier',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicalstudyterminationconclusion',
            name='parent_tracking_identifier',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicalstudyterminationconclusion',
            name='related_tracking_identifier',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicalstudyterminationconclusionw10',
            name='parent_tracking_identifier',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicalstudyterminationconclusionw10',
            name='related_tracking_identifier',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='protocoldeviationviolation',
            name='parent_tracking_identifier',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='protocoldeviationviolation',
            name='related_tracking_identifier',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='studyterminationconclusion',
            name='parent_tracking_identifier',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='studyterminationconclusion',
            name='related_tracking_identifier',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='studyterminationconclusionw10',
            name='parent_tracking_identifier',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='studyterminationconclusionw10',
            name='related_tracking_identifier',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='deathreport',
            name='action_identifier',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='deathreport',
            name='subject_identifier',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='deathreporttmg',
            name='action_identifier',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='deathreporttmg',
            name='subject_identifier',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historicaldeathreport',
            name='action_identifier',
            field=models.CharField(db_index=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='historicaldeathreport',
            name='subject_identifier',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='historicaldeathreporttmg',
            name='action_identifier',
            field=models.CharField(db_index=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='historicaldeathreporttmg',
            name='subject_identifier',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalprotocoldeviationviolation',
            name='action_identifier',
            field=models.CharField(db_index=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='historicalprotocoldeviationviolation',
            name='subject_identifier',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalstudyterminationconclusion',
            name='action_identifier',
            field=models.CharField(db_index=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='historicalstudyterminationconclusion',
            name='subject_identifier',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalstudyterminationconclusionw10',
            name='action_identifier',
            field=models.CharField(db_index=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='historicalstudyterminationconclusionw10',
            name='subject_identifier',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='protocoldeviationviolation',
            name='action_identifier',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='protocoldeviationviolation',
            name='subject_identifier',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studyterminationconclusion',
            name='action_identifier',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='studyterminationconclusion',
            name='subject_identifier',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='studyterminationconclusionw10',
            name='action_identifier',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='studyterminationconclusionw10',
            name='subject_identifier',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
