# Generated by Django 2.1 on 2018-10-01 21:31

import ambition_prn.models.death_report_tmg
from django.db import migrations
import edc_base.sites.managers
import edc_identifier.managers


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_prn', '0007_auto_20181001_2103'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='deathreport',
            managers=[
                ('on_site', edc_base.sites.managers.CurrentSiteManager()),
                ('objects', edc_identifier.managers.SubjectIdentifierManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='deathreporttmg',
            managers=[
                ('on_site', edc_base.sites.managers.CurrentSiteManager()),
                ('objects', ambition_prn.models.death_report_tmg.DeathReportTmgManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='onschedule',
            managers=[
                ('on_site', edc_base.sites.managers.CurrentSiteManager()),
                ('objects', edc_identifier.managers.SubjectIdentifierManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='onschedulew10',
            managers=[
                ('on_site', edc_base.sites.managers.CurrentSiteManager()),
                ('objects', edc_identifier.managers.SubjectIdentifierManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='protocoldeviationviolation',
            managers=[
                ('on_site', edc_base.sites.managers.CurrentSiteManager()),
                ('objects', edc_identifier.managers.TrackingIdentifierManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='studyterminationconclusion',
            managers=[
                ('on_site', edc_base.sites.managers.CurrentSiteManager()),
                ('objects', edc_identifier.managers.SubjectIdentifierManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='studyterminationconclusionw10',
            managers=[
                ('on_site', edc_base.sites.managers.CurrentSiteManager()),
                ('objects', edc_identifier.managers.SubjectIdentifierManager()),
            ],
        ),
    ]
